name: CI
on:
  push:
    tags: ["v*"]
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  ci:
    uses: tinyland-inc/ci-templates/.github/workflows/npm-publish.yml@main
    secrets: inherit
